### ISSUE TITLE
No options available in the GUI

### ISSUE THREAD

**Issue by MrSleeps** [thomasloven/lovelace-layout-card#241]
My Home Assistant version: 
2023.3.6

Layout-card version: 
2.4.4

What I am doing: 
Trying to to access the GUI options

What I expected to happen:
The gui options show and no console errors?

What happened instead:
No options available and console errors are showing

Error messages from the browser console:

`Uncaught (in promise) TypeError: this._config.cards is not iterable
    at Mt.setConfig (layout-card.js:13:443)`

`layout-card.js:13 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'disconnect')
    at Mt._makeColumnLayout (layout-card.js:13:4088)
    at Mt._makeLayout (layout-card.js:13:4018)
    at Mt.updated (layout-card.js:13:1246)`

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'disconnect')
    at Mt._makeColumnLayout (layout-card.js:13:4088)
    at Mt._makeLayout (layout-card.js:13:4018)
    at Mt.updated (layout-card.js:13:1285)`

`layout-card.js:13 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'disconnect')
    at Mt._makeColumnLayout (layout-card.js:13:4088)
    at Mt._makeLayout (layout-card.js:13:4018)
    at Mt.updated (layout-card.js:13:1446)`
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by jalejandro0211** [comment]
Same issue, did you salve?

**Comment by MrSleeps** [comment]
Nope

**Comment by Taomyn** [comment]
Installed this today on:

Home Assistant 2023.5.1
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.2 - latest

![image](https://user-images.githubusercontent.com/4365929/236449879-99a5bbc6-0447-48d3-a592-59ce9e07d760.png)


Have the exact same issue, change to the new view but after saving the new layout options box does not appear. I tried adding the values to the main yaml of the view but it didn't have any effect on it. Basically it's no different to the stock view.

**Comment by jalejandro0211** [comment]
> Installed this today on:
> 
> Home Assistant 2023.5.1 Supervisor 2023.04.1 Operating System 10.1 Frontend 20230503.2 - latest
> 
> ![image](https://user-images.githubusercontent.com/4365929/236449879-99a5bbc6-0447-48d3-a592-59ce9e07d760.png)
> 
> Have the exact same issue, change to the new view but after saving the new layout options box does not appear. I tried adding the values to the main yaml of the view but it didn't have any effect on it. Basically it's no different to the stock view.

Same here...

`2023-05-05 08:32:20.521 ERROR (MainThread) [frontend.js.latest.202305032] http://homeassistant:8123/hacsfiles/lovelace-layout-card/layout-card.js?hacstag=156434866244:13:3317 Uncaught TypeError: Cannot read properties of undefined (reading 'disconnect')
`

**Comment by Tomadoggy** [comment]
Same here, layout option not showing 
![image](https://github.com/thomasloven/lovelace-layout-card/assets/62314433/ad4dacb5-8445-4169-b2ea-1da50b258116)

**Comment by quadcom** [comment]
Yup, I really would like to get grid working in the UI here. Way more flexible in layout potential

**Comment by bert269** [comment]
I have the same problem. I have it showing up in HACS: (honestly - I could not remember when I installed this through HACS). 
![image](https://github.com/thomasloven/lovelace-layout-card/assets/18601216/66ee8e04-a95e-4b4e-8ec8-e01116b372e5)

But nevermind - it does not seem to work:
![image](https://github.com/thomasloven/lovelace-layout-card/assets/18601216/51c6625e-b0a6-4083-b309-39716395f693)
As you can see, the option does not show up.

Then I followed the instructions (left it in HACS) and copied the RAW layout-card.js to the www directory and configure it as /local/layout-card, selected Javascript as the option and it is listed:
![image](https://github.com/thomasloven/lovelace-layout-card/assets/18601216/9d582d0b-97a1-4f26-b5da-5058b45d5598)

I refreshed the browser page. I even restarted the browser.
I still do not see the option when editing a dashboard.

Please help

**Comment by bert269** [comment]
NEVERMIND - sorry.
![image](https://github.com/thomasloven/lovelace-layout-card/assets/18601216/f6820067-c047-4891-98f7-04143b88eed6)
